---
kind: Template
apiVersion: v1
labels:
  app: "${NAME}"
  app.kubernetes.io/component: "${NAME}"
  app.kubernetes.io/instance: "${NAME}"
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: java
  app.kubernetes.io/part-of: "${NAME}"
  template: "${NAME}-nsp-template"
metadata:
  name: "${NAME}"
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: "${NAME}-${TARGET_NAME}-${TARGET_INSTANCE}-readonly-${TARGET_NAMESPACE}-comms"
    spec:
      description: |
        Allow metabase pods to open connections to patroni cluster pods in other namespaces
      source:
        - - "$namespace=${NAMESPACE}"
          - "app=${NAME}"
          - "deploymentconfig=${NAME}"
      destination:
        - - "$namespace=${TARGET_NAMESPACE}"
          - "cluster-name=${TARGET_INSTANCE}"
          - "role=replica"
          - "app.kubernetes.io/name=${TARGET_NAME}"
parameters:
  - name: NAME
    description: The name assigned to all of the objects defined in this template
    displayName: Name
    required: true
    value: metabase
  - name: NAMESPACE
    description: Namespace this NSP will reside in (i.e. 'a7f51d-tools')
    displayName: Namespace
    required: true
  - name: TARGET_NAME
    description: The name of the application db to grant access to
    displayName: Application Name
    required: true
    value: patroni
  - name: TARGET_INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
    value: master
  - name: TARGET_NAMESPACE
    description: Namespace of the target database (i.e. 'a7f51d-dev')
    displayName: Namespace
    required: true
